theme = "custom"

[editor]
bufferline = "always"
line-number = "relative"
mouse = false
true-color = true
scrolloff = 0
auto-format = false

[editor.statusline]
left = ["mode", "file-name", "version-control", "read-only-indicator", "file-modification-indicator", "spinner"]
center = []
right = ["diagnostics", "register", "primary-selection-length", "position", "position-percentage", "file-encoding", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "all"

[editor.soft-wrap]
enable = true

[keys.normal.space]
del = ":buffer-close!"
